services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            -   ./:/var/www
        networks:
            -   laravel
        env_file:
            -   .env

    webserver:
        image: nginx:1.26.0-alpine
        container_name: nginx
        ports:
            -   "8081:80"
        volumes:
            -   ./:/var/www
            -   ./nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            -   app
        networks:
            -   laravel

    db:
        image: mariadb:latest
        container_name: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            -   dbdata:/var/lib/mysql
        ports:
            -   "3307:3306"
        networks:
            -   laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        ports:
            -   "8082:80"
        depends_on:
            -   db
        networks:
            -   laravel

networks:
    laravel:

volumes:
    dbdata:
