name: Laravel Tests

on:
  push:
    branches:
      - main  # Déclencher les tests sur le push vers la branche main
  pull_request:
    branches:
      - main  # Déclencher les tests sur les pull requests vers la branche main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
          MYSQL_USER: laravel
          MYSQL_PASSWORD: laravel
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'  # Changer à la version PHP utilisée dans ton projet

      - name: Install dependencies
        run: |
          cp .env.example .env
          composer install --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader
          php artisan key:generate
          php artisan config:cache

      - name: Run tests
        run: php artisan test
